### ISSUE TITLE
Tailwind Intellisense doesn't seem to work

### ISSUE THREAD

**Issue by gsimone** [brattonross/windy-radix-palette#12]
Hey! Awesome little utility, very thankful for it 🙏 

Does the tailwind intellisense extension pickup the colors for you?

<img width="312" alt="image" src="https://user-images.githubusercontent.com/1862172/213140377-cb03595f-b029-4256-af6a-38c051104278.png">

As you can see in the screen, it's working fine with the default colors  and colors added explicitly in the theme (the `test` color).

Not sure if this is a bug on your end or a more general problem with tw intellisense, honestly.

Thanks again for this lil' project, have a great day!

**Comment by brattonross** [comment]
I'm aware that intellisense doesn't pick up the colors, someone found the same problem before (#9). I'm not sure exactly how the extension picks up the color, I would guess that it's because the colors are defined using CSS variables, but maybe I'm wrong.

I would be interested to see if this gets fixed by the implementation of #13

**Comment by Gravy59** [comment]
> I would be interested to see if this gets fixed by the implementation of https://github.com/brattonross/windy-radix-palette/issues/13

It's still reading a css variable so I don't expect any change. However, the vars are added to the `@tailwind base` so maybe intellisense can figure that out?

**Comment by brattonross** [comment]
I think getting colors to show up in Tailwind Intellisense is probably not  possible with the way that this plugin currently works.

As I understand it, since the colors are defined CSS variables, the Intellisense plugin doesn't know how to display it, and we rely on using CSS variables so that we can switch out the values based on light/dark mode.

I'd still accept a PR if someone figures out how to get it to work, but my gut tells me that it's more an issue with Tailwind Intellisense than it is with this plugin.
